# Generated by Django 3.0.4 on 2020-05-29 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('event_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('uni_id', models.IntegerField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('participants', models.CharField(max_length=200)),
                ('creditor', models.CharField(default=' ', max_length=20)),
                ('total_loan_sum', models.FloatField(null=True)),
                ('payment_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('creator', models.CharField(blank=True, default=' ', max_length=20)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Event')),
            ],
        ),
    ]
