# Generated by Django 3.0.4 on 2020-06-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200602_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='percents_type',
            field=models.IntegerField(choices=[(1, 'Простые'), (2, 'Сложные')], default=1),
        ),
    ]
