# Generated by Django 3.0.4 on 2020-06-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_payment_percents_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='percents',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='percents_type',
            field=models.IntegerField(choices=[(1, 'Отсутствуют'), (2, 'Простые'), (3, 'Сложные')], default=1),
        ),
    ]
