# Generated by Django 3.0.4 on 2020-06-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_payment_sum_with_percents'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='period',
            field=models.IntegerField(default=1),
        ),
    ]
