# Generated by Django 3.0.4 on 2020-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_payment_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='period',
            field=models.IntegerField(default=0),
        ),
    ]
