# Generated by Django 3.0.4 on 2020-06-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200605_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='x',
        ),
        migrations.RemoveField(
            model_name='event',
            name='y',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='x',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='y',
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
